version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=mamang
      - POSTGRES_PASSWORD=mamang
      - POSTGRES_DB=mytest

  db:
    image: postgres:14.7-alpine3.17
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=mamang
      - POSTGRES_PASSWORD=mamang
      - POSTGRES_DB=mytest
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
